sudo: false
language: python
python: 3.7
script:
- "./test.sh"
- "./build.sh"
deploy:
  provider: pypi
  skip_cleanup: true
  user: hardwario
  on:
    tags: true
  password:
    secure: AhOMmoIO9jhW1BRdsDhZ6kW7WJqTOh9Bf7Lcgvk0bJjCp3fx7WC0N8WUo76dxD4qiRcx50ik/kdTZQGLCKnvsKARG0Oxitp3lneFJxawekld5tNywWRwtGLXIRVL3DL1M31DqHO3MwH35WDMXD62/UthFp+OXr6dLMhjaA+P+MftQ7kvHuEXzLL8KI6W9cwBtgly1Ny7w4OUr+VHgh7w9c6sc+WYmQERDh0SZQv4qRxTF60ViQYHjIFaD7FVWJsBnzvW6cXiV6X7XSGtdMlHkUda1w+vbUQoKRIDbluf3gsspY2tVC0R4950qWJuXZVyGKv9mcU2otfE37hKyIGxNK5M7XxlpUIGaFgSy8ykR8F0jpvsHn4z2cHh8Xip3fn1qWlbwGdN+A2TDijp+h7xTC9UtZoH50ZWDFvAe57AiX2FGuD4bbc3NuoPjIu8ubCVnxCa3zrFkEu3hc7HFh1jK2isFNa1EvvQifUJZRV9/BLNw5i0XJCnWuTPWK7az+4mslipH9MXnFlJL1d2MIgmjFwblhOCw9sLx220v1qLSkwDhoq1mEeaeSr7NK5hGlE4SiwLjAyj4wjuFBhv0siI8eYUruAQIqHytbfugSgXt2ERJe/wyoLsgW8pRQYP6OAAfPBsch/K/n5+Yf90IRGqjfDKLPjVVG7ZSZkpLalAZLU=
